### ISSUE TITLE
How to enable FGP (Fine Grained Parallelism) in VCS simulation

### ISSUE THREAD

**Issue by SihaoLiu** [ucb-bar/chipyard#1081]
According to VCS user guide,

```
Two-step flow:
% vcs -fgp -full64 <otherOptions> 
% simv -fgp=num_threads:<value>
```

By adding `-fgp` option to vcs and simv, we might be able to speed up the simulation. I would like to know is it possible for chipyard flow? I tried to add `-fpg` related to `vcs`, the compilation seems working (compile command looks like: 
`vcs -fgp -full64 -CFLAGS " -O3 -std=c++11 -I/home ...`

But when I tried to run binary simulation with : `make CONFIG=... EXTRA_SIM_FLAGS=-fgp=num_threads:8 BINARY=...`

It failed with error:

```
Error-[DPI-UED] C++ Exception detected
  Import DPI routine invoked at file
  '/home/sihao/repo/chipyard/sims/vcs/generated-src/chipyard.TestHarness.MeshDSARocketConfig/SimSerial.v'(line
  53) has C++ exceptions not caught. C++ exceptions shall not propagate out of
  any imported subroutine.
  Fix it in DPI-C code before running simulation.
```

I would like to know would it be easy to enable fine-grained parallelism in current flow? If so, how should I enable it? If not, where should I hack?

Thank you so much in advance!

**Comment by jerryz123** [comment]
I believe this is due to how HTIF is parsing arguments. https://github.com/riscv-software-src/riscv-isa-sim/blob/e93b9cbbbcd3ad0a02ae298e9f1a2d98d3ac0153/fesvr/htif.cc#L252 . I believe `getopt_long` is treating `-fgp`... as option characters, equivalent to `-f -g -p`.

I think the best solution to this is to modify the initialization of `testchip_tsi_t` to remove the `-fgp` flag from the argc, argv that is passed to the base class constructor. The inheritance structure is `testchip_tsi_t < tsi_t < htif_t`.

**Comment by SihaoLiu** [comment]
I see, thanks! I will take a look.

**Comment by SihaoLiu** [comment]
PR https://github.com/ucb-bar/testchipip/pull/141 created
