### ISSUE TITLE
Stop calling everything "BoomAndRocketX"

### ISSUE THREAD

**Issue by jerryz123** [ucb-bar/chipyard#153]

**Comment by colinschmidt** [comment]
It does seem redundant if everything has that prefix

**Comment by abejgonzalez** [comment]
"Blocket" system. https://github.com/riscv-boom/riscv-boom/pull/323

**Comment by jwright6323** [comment]
I'm also not a fan of the long name, but serious question: what happens when we have a 3rd core and/or you start making `BoomSystolic` and `BoomHwacha` configs (without Rocket)? What about `RocketHbwif` and `BoomHbwif`, `RocketMyCoolWidget` and `BoomMyCoolWidget`, ... ?

**Comment by abejgonzalez** [comment]
The long name was a short term solution to the naming problem. For the subsystem, I think it make a bit of sense. However for configs, I agree it gets too verbose. Maybe do what others do and just make it so that if you want boom and a systolic array you have the mixins and use them with the underscore to combine in the generator (a.k.a `make CONFIG=SmallBoomConfig_WithSystolicArray_WithWowWidget`)

**Comment by jwright6323** [comment]
I like that, but if you have `CONFIG=SmallBoomAndRocketConfig_WithSystolicArray` what core gets the systolic array?

**Comment by colinschmidt** [comment]
I think the underscores can be a solution but we need to make sure we can create reasonable options.

**Comment by jwright6323** [comment]
I'm not super familiar with the `site, here, up` shenanigans, but can you make a config would attach to previously config'ed cores? e.g. something like (spitballing a bit):

`SmallBoomConfig_WithAnotherRocket`
=> Boom and Rocket
vs.
`SmallBoomConfig_WithSystolicArray_WithAnotherRocket`
=> (Boom + Systolic) and Rocket
vs.
`SmallBoomConfig_WithSystolicArray_WithAnotherRocket_WithHwacha`
=>  (Boom + Systolic) and (Rocket + Hwacha)
vs.
`SmallBoomConfig_WithSystolicArray_WithAnotherRocket_WithSystolicArray`
=>  (Boom + Systolic) and (Rocket + Systolic)

**Comment by abejgonzalez** [comment]
Yes. You can do that.

**Comment by jwright6323** [comment]
Which names?

**Comment by abejgonzalez** [comment]
Sorry. I was not clear at all. Thinking about how people interact with the configs, we will probably have to change the output names for things such as the folders, simulator names since these will make the current system very clunky. We should also change the name to be something like how we currently compose things... `BaseConfig_WithLargeBoom_WithNormalHwacha_WithSmallRocket_WithLargeSystolic`.

**Comment by abejgonzalez** [comment]
Solved if #211 is merged.
