### ISSUE TITLE
Verilator make run-fast fails on Sha3RocketConfig

### ISSUE THREAD

**Issue by 20dy3** [ucb-bar/chipyard#325]
Hi,

We are students trying to run Verilator benchmarks for the Rocket Core with the Sha3 RoCC example accelerator. However, we're running into this issue:

<img width="1279" alt="Screen Shot 2019-11-04 at 4 02 54 PM" src="https://user-images.githubusercontent.com/43714419/68158835-7cd5d100-ff1e-11e9-8588-798da8914cf6.png">

This timeout problem consistently happens, even when we increase the threshold on `max-cycles` etc.

We followed the documentation [here](https://chipyard.readthedocs.io/en/latest/) and [here](https://chipyard.readthedocs.io/en/latest/Simulation/Software-RTL-Simulation.html#). `make CONFIG=Sha3RocketConfig` seems to work correctly, and the benchmarks run successfully on the vanilla Rocket Core with `make run-fast`.

Thanks in advance!

**Comment by abejgonzalez** [comment]
Hi,

On the `dev` branch of Chipyard, I just ran `make CONFIG=Sha3RocketConfig run-asm-tests` and `run-bmark-tests` and `run-fast` and all three passed. It looks like you are using the `esp-tools` toolchain. You should use the normal toolchain since `esp-tools` is mainly used for Hwacha. Otherwise, can you give more information on what your environment is?

**Comment by 20dy3** [comment]
Thanks, not using `esp-tools` seems to work.
